import { useQuery } from '@tanstack/react-query';
import { getRoadmaps } from '../lib/api';
import { Link } from 'react-router';
import { BookOpen, ChevronRight, FileText } from 'lucide-react';
import { motion } from 'framer-motion';

export default function Roadmap() {
  const { data: roadmaps, isLoading } = useQuery({
    queryKey: ['roadmaps'],
    queryFn: () => getRoadmaps(false),
  });

  if (isLoading) {
    return (
      <div className="flex h-64 items-center justify-center">
        <div className="h-8 w-8 animate-spin rounded-full border-4 border-blue-600 border-t-transparent"></div>
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-4xl px-4 py-12 sm:px-6 lg:px-8">
      <div className="mb-12 text-center">
        <h1 className="text-4xl font-extrabold tracking-tight text-slate-900 sm:text-5xl">
          Interactive Roadmaps
        </h1>
        <p className="mt-4 text-xl text-slate-600">
          Industry-relevant learning paths generated by AI.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        {roadmaps?.map((roadmap, index) => (
          <motion.div 
            key={roadmap._id} 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: index * 0.1 }}
            className="rounded-2xl border border-slate-200 bg-white p-8 shadow-sm hover:shadow-md transition-shadow flex flex-col h-full"
          >
            <div className="flex items-center gap-3 mb-4">
              <div className="p-3 bg-indigo-100 rounded-xl">
                <FileText className="w-6 h-6 text-indigo-600" />
              </div>
              <h2 className="text-2xl font-bold text-slate-900">{roadmap.title}</h2>
            </div>
            
            <p className="mb-6 text-slate-600 flex-1">{roadmap.description}</p>
            
            <div className="flex items-center justify-between mb-8 text-sm font-medium text-slate-500">
              <span className="bg-slate-100 px-3 py-1.5 rounded-lg">Role: {roadmap.role}</span>
              <span className="bg-slate-100 px-3 py-1.5 rounded-lg">{roadmap.phases?.length || 0} Phases</span>
            </div>
            
            <Link 
              to={`/roadmaps/${roadmap.slug}`}
              className="w-full flex items-center justify-center gap-2 rounded-xl bg-indigo-600 px-4 py-3 text-sm font-semibold text-white hover:bg-indigo-700 transition-colors mt-auto"
            >
              <BookOpen className="w-4 h-4" />
              Explore Roadmap
              <ChevronRight className="w-4 h-4" />
            </Link>
          </motion.div>
        ))}
        {(!roadmaps || roadmaps.length === 0) && (
          <div className="col-span-1 md:col-span-2 text-center py-12 text-slate-500 bg-slate-50 rounded-2xl border border-dashed border-slate-200">
            No roadmaps available yet. Check back soon!
          </div>
        )}
      </div>
    </div>
  );
}
